<a href="https://colab.research.google.com/github/ilaydasevgi/ilayda_sevgi-Math-2024-25-Winter/blob/main/ilayda_sevgi_LA_Matrix_triangular_en.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Define the matrices A and B
A = np.array([[12, 3],
              [-18, -4]])

B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Function to perform Gaussian elimination and reduce matrix to upper triangular form
def upper_triangular(matrix):
    n = len(matrix)
    for i in range(n):
        # Make the diagonal contain all 1's
        factor = matrix[i, i]
        matrix[i] = matrix[i] / factor

        # Make the elements below the diagonal 0
        for j in range(i + 1, n):
            factor = matrix[j, i]
            matrix[j] = matrix[j] - factor * matrix[i]
    return matrix

# Function to calculate determinant by multiplying the diagonal elements
def determinant_from_upper(matrix):
    return np.prod(np.diag(matrix))

# Reduce matrices A and B to upper triangular form
upper_A = upper_triangular(np.copy(A).astype(float))
upper_B = upper_triangular(np.copy(B).astype(float))

# Calculate the determinants
det_A = determinant_from_upper(upper_A)
det_B = determinant_from_upper(upper_B)

# Output the results
print("Upper triangular form of A:")
print(upper_A)

print("\nDeterminant of A:", det_A)

print("\nUpper triangular form of B:")
print(upper_B)

print("\nDeterminant of B:", det_B)

Upper triangular form of A:
[[1.   0.25]
 [0.   1.  ]]

Determinant of A: 1.0

Upper triangular form of B:
[[ 1.  2.  3.]
 [-0.  1.  2.]
 [nan nan nan]]

Determinant of B: nan


<ipython-input-1-c2f4b65aa2ca>:17: RuntimeWarning: invalid value encountered in divide
  matrix[i] = matrix[i] / factor
